In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
import timestring
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

We have two datasets here from the CMS State Drug Utilization Set
<li>CMS State Drug Utilization Data 2017<br>   
<li>CMS State Drug Utilization Data 2016
<li>Ref for product codes: https://data.medicaid.gov/State-Drug-Utilization/State-Drug-Utilization-Data-2016/3v6v-qk5s
<li>About CMS Product Codes: 
<li>Labeler Code: First segment of NDC that identifies the manufacturer, labeler, relabeler, packager, repackager or distributor of the drug.
<li>Product Code: Second segment of NDC.
<li>Package Size Code: Third segment of NDC.

Drug names for opioids:<br>

REFERENCE: http://www.rehabcenter.net/list-opioids-united-states/

Brand Name Opioid Prescriptions:
    
For this dataset, you need to look up and filter down the opioid-related drugs. If you do this through
the Product Name, I used this set of opioid Rx drugs: 

<li>Abstral (fentanyl)
<li>Actiq (fentanyl)
<li>Avinza (morphine sulfate extended-release capsules)
<li>Butrans (buprenorphine transdermal system)
<li>Demerol (meperidine [also known as isonipecaine or pethidine])
<li>Dilaudid (hydromorphone [also known as dihydromorphinone])
<li>Dolophine (methadone hydrochloride tablets)
<li>Duragesic (fentanyl transdermal system)
<li>Fentora (fentanyl)
<li>Hysingla (hydrocodone)
<li>Methadose (methadone)
<li>Morphabond (morphine)
<li>Nucynta ER (tapentadol extended-release oral tablets)
<li>Onsolis (fentanyl)
<li>Oramorph (morphine)
<li>Oxaydo (oxycodone)
<li>Roxanol-T (morphine)
<li>Sublimaze (fentanyl)
<li>Xtampza ER (oxycodone)
<li>Zohydro ER (hydrocodone)

Combination Opioid Prescriptions:<br>

<li>Anexsia (hydrocodone containing acetaminophen)
<li>Co-Gesic (hydrocodone containing acetaminophen)
<li>Embeda (morphine sulfate and naltrexone extended-release capsules)
<li>Exalgo (hydromorphone hydrochloride extended-release tablets)
<li>Hycet (hydrocodone containing acetaminophen)
<li>Hycodan (hydrocodone containing homatropine)
<li>Hydromet (hydrocodone containing homatropine)
<li>Ibudone (hydrocodone containing ibuprofen)
<li>Kadian (morphine sulfate extended-release tablets)
<li>Liquicet (hydrocodone containing acetaminophen)
<li>Lorcet (hydrocodone containing acetaminophen)
<li>Lorcet Plus (hydrocodone containing acetaminophen)
<li>Lortab (hydrocodone containing acetaminophen)
<li>Maxidone (hydrocodone containing acetaminophen)
<li>MS Contin (morphine sulfate controlled-release tablets)
<li>Norco (hydrocodone containing acetaminophen)
<li>Opana ER (oxymorphone hydrochloride extended-release tablets)
<li>OxyContin (oxycodone hydrochloride controlled-release tablets)
<li>Oxycet (oxycodone containing acetaminophen)
<li>Palladone (hydromorphone hydrochloride extended-release capsules)
<li>Percocet (oxycodone containing acetaminophen)
<li>Percodan (oxycodone containing aspirin)
<li>Reprexain (hydrocodone containing ibuprofen)
<li>Rezira (hydrocodone containing pseudoephedrine)
<li>Roxicet (oxycodone containing acetaminophen)
<li>Targiniq ER (oxycodone containing naloxone)
<li>TussiCaps (hydrocodone containing chlorpheniramine)
<li>Tussionex (hydrocodone containing chlorpheniramine)
<li>Tuzistra XR (codeine containing chlorpheniramine)
<li>Tylenol #3 and #4 (codeine containing acetaminophen)
<li>Vicodin (hydrocodone containing acetaminophen)
<li>Vicodin ES (hydrocodone containing acetaminophen)
<li>Vicodin HP (hydrocodone containing acetaminophen)
<li>Vicoprofen (hydrocodone containing ibuprofen)
<li>Vituz (hydrocodone containing chlorpheniramine)
<li>Xartemis XR (oxycodone containing acetaminophen)
<li>Xodol (hydrocodone containing acetaminophen)
<li>Zolvit (hydrocodone containing acetaminophen)
<li>Zutripro (hydrocodone containing chlorpheniramine and pseudoephedrine)
<li>Zydone (hydrocodone containing acetaminophen)

Generic: <br>

<li>Fentanyl (fentanyl extended-release transdermal system)
<li>Methadone hydrochloride (methadone hydrochloride tablets, methadone hydrochloride oral solution)
<li>Morphine sulfate (morphine sulfate extended-release capsules, morphine sulfate extended-release tablets)
<li>Oxymorphone hydrochloride (oxymorphone hydrochloride extended-release tablets)

In [2]:
#CMS
cms_2017 = pd.read_csv("/Users/catherineordun/Documents/Hackathon/DHHS/ready_data/State_Drug_Utilization_Data_2017.csv")
print(cms_2017.shape) #(2343727, 20)
cms_2017.dtypes

(2343727, 20)

Utilization Type                   object
State                              object
Labeler Code                        int64
Product Code                        int64
Package Size                        int64
Year                                int64
Quarter                             int64
Product Name                       object
Suppression Used                     bool
Units Reimbursed                  float64
Number of Prescriptions           float64
Total Amount Reimbursed           float64
Medicaid Amount Reimbursed        float64
Non Medicaid Amount Reimbursed    float64
Quarter Begin                      object
Quarter Begin Date                 object
Latitude                          float64
Longitude                         float64
Location                           object
NDC                                 int64
dtype: object

In [3]:
cms_2017.rename(columns={
        'Labeler Code':'label_code',
        'Product Code':'product_code',
        'Package Size':'package_size',
        'Product Name':'product_name',
        'Suppression Used':'suppression',
        'Units Reimbursed':'units_reimb',
        'Number of Prescriptions':'num_rx',
        'Total Amount Reimbursed':'total_amt_reimb',
        'Medicaid Amount Reimbursed':'med_amt_reimb',
        'Non Medicaid Amount Reimbursed':'nonmed_amt_reimb',
        'Quarter Begin':'qtr_begin', 
        'Quarter Begin Date':'qtr_begin_date'},inplace=True)

In [5]:
cms_2017.loc[(cms_2017["product_name"] == "PERCOCET")]

,Utilization Type,State,label_code,product_code,package_size,Year,Quarter,product_name,suppression,units_reimb,num_rx,total_amt_reimb,med_amt_reimb,nonmed_amt_reimb,qtr_begin,qtr_begin_date,Latitude,Longitude,Location,NDC
84839,MCOU,XX,63481,627,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,NaN,NaN,NaN,63481062770
118099,FFSU,NC,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",63481062370
169729,MCOU,NH,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,43.4108,-71.5653,"(43.4108, -71.5653)",63481062970
272821,FFSU,MN,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062370
311125,MCOU,MN,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062370
356253,FFSU,MO,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,38.4623,-92.3020,"(38.4623, -92.302)",63481062370
362239,FFSU,CO,63481,628,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,39.0646,-105.3272,"(39.0646, -105.3272)",63481062870
372935,MCOU,MN,63481,627,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062770
384674,FFSU,NC,63481,628,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",63481062870
447304,FFSU,XX,63481,623,85,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,NaN,NaN,NaN,63481062385
468636,MCOU,KY,63481,623,85,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",63481062385
488994,MCOU,FL,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,27.8333,-81.7170,"(27.8333, -81.717)",63481062970
546028,MCOU,FL,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,27.8333,-81.7170,"(27.8333, -81.717)",63481062370
617166,FFSU,KY,63481,623,85,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",63481062385
622136,MCOU,NH,63481,628,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,43.4108,-71.5653,"(43.4108, -71.5653)",63481062870
714198,MCOU,AZ,63481,623,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,33.7712,-111.3877,"(33.7712, -111.3877)",63481062370
750483,FFSU,MN,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062970
753482,FFSU,NC,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",63481062970
779988,MCOU,MI,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,43.3504,-84.5603,"(43.3504, -84.5603)",63481062970
919401,FFSU,KY,63481,623,85,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",63481062385
971294,FFSU,MO,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,38.4623,-92.3020,"(38.4623, -92.302)",63481062370
1045691,MCOU,FL,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,27.8333,-81.7170,"(27.8333, -81.717)",63481062370
1087263,FFSU,NC,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",63481062970
1106830,FFSU,NC,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",63481062370
1215471,MCOU,NH,63481,628,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.4108,-71.5653,"(43.4108, -71.5653)",63481062870
1240532,MCOU,KY,63481,623,85,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",63481062385
1283047,FFSU,NH,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.4108,-71.5653,"(43.4108, -71.5653)",63481062370
1446596,FFSU,CO,63481,628,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,39.0646,-105.3272,"(39.0646, -105.3272)",63481062870
1586055,MCOU,FL,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,27.8333,-81.7170,"(27.8333, -81.717)",63481062970
1616465,FFSU,MI,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.3504,-84.5603,"(43.3504, -84.5603)",63481062370
1643733,MCOU,MI,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.3504,-84.5603,"(43.3504, -84.5603)",63481062970
1697886,MCOU,MN,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062370
1892110,FFSU,MN,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062370
1913831,MCOU,NH,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.4108,-71.5653,"(43.4108, -71.5653)",63481062970
1933971,FFSU,MN,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062970
2025877,MCOU,MN,63481,629,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",63481062970
2112221,MCOU,AZ,63481,623,70,2017,2,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,33.7712,-111.3877,"(33.7712, -111.3877)",63481062370
2156528,MCOU,AZ,63481,629,70,2017,1,PERCOCET,True,NaN,NaN,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,33.7712,-111.3877,"(33.7712, -111.3877)",63481062970

You'll notice here that the Labeler Code + Product Code is equal to in the
nda_product file the following: 
    
<li>PRODUCTNDC: 57881-332	

In order to determine the packagem dosage, and manufacturer, you need to merge together the product 
and package files from the NDA at FDA.

In [6]:
#this is a different dataset from the FDA
nda_product = pd.read_csv("/Users/catherineordun/Documents/Hackathon/DHHS/nda_product.csv")

In [7]:
nda_product.head()

,PRODUCTID,PRODUCTNDC,PRODUCTTYPENAME,PROPRIETARYNAME,PROPRIETARYNAMESUFFIX,NONPROPRIETARYNAME,DOSAGEFORMNAME,ROUTENAME,STARTMARKETINGDATE,ENDMARKETINGDATE,MARKETINGCATEGORYNAME,APPLICATIONNUMBER,LABELERNAME,SUBSTANCENAME,ACTIVE_NUMERATOR_STRENGTH,ACTIVE_INGRED_UNIT,PHARM_CLASSES,DEASCHEDULE
0,0363-0810_298b1eeb-c214-4d67-8c7f-4682bac2cf23,0363-0810,HUMAN OTC DRUG,70%,NaN,Isopropyl alcohol,LIQUID,TOPICAL,19891015.0,NaN,OTC MONOGRAPH NOT FINAL,part333A,"Walgreens, CO.",ISOPROPYL ALCOHOL,500,mg/mL,NaN,NaN
1,0574-0067_cba29e3c-d446-4a70-928a-c98ed8eedcc6,0574-0067,HUMAN OTC DRUG,70%,NaN,Isopropyl alcohol,LIQUID,TOPICAL,20140414.0,NaN,OTC MONOGRAPH NOT FINAL,part333A,"Paddock Laboratories, LLC",ISOPROPYL ALCOHOL,500,mg/mL,NaN,NaN
2,11673-810_fe48f8bd-77f0-487b-b24f-217a3601fd62,11673-810,HUMAN OTC DRUG,70%,NaN,Isopropyl alcohol,LIQUID,TOPICAL,19890715.0,NaN,OTC MONOGRAPH NOT FINAL,part333A,"Target Corp.,",ISOPROPYL ALCOHOL,500,mg/mL,NaN,NaN
3,37012-810_3eedb9fd-22af-4650-b110-459d644f47dd,37012-810,HUMAN OTC DRUG,70%,NaN,Isopropyl alcohol,LIQUID,TOPICAL,20080102.0,NaN,OTC MONOGRAPH NOT FINAL,part333A,Shopko Stores Operating Co,ISOPROPYL ALCOHOL,500,mg/mL,NaN,NaN
4,37808-810_e723ebfd-b701-4f61-aedc-d6d93d277ac8,37808-810,HUMAN OTC DRUG,70%,NaN,Isopropyl alcohol,LIQUID,TOPICAL,20150618.0,NaN,OTC MONOGRAPH NOT FINAL,part333A,H-E-B,ISOPROPYL ALCOHOL,500,mg/mL,NaN,NaN

Steps:<br>
#1. Now, we need to extract out from the cms_2017 file, all the drugs that are opioid drugs 
#2. Create a new field called PRODUCTNDC
#3. And merge with nda_product to get the dosage and manufacturer name
#4. Convert the 'STARTMARKETINGDATE' from float -> datetime

In [8]:
#these are all the drugs listed above in a csv
druglist= pd.read_csv("/Users/catherineordun/Documents/Hackathon/DHHS/druglist.csv")

In [9]:
druglist.head()

   Abstral
0  Abstral
1    Actiq
2   Avinza
3  Butrans
4  Demerol

In [10]:
#flatten to remove it as a list of lists
searchlist = druglist.values.T.flatten()

In [13]:
searchlist

array(['Abstral', 'Actiq', 'Avinza', 'Butrans', 'Demerol', 'Dilaudid',
       'Dolophine', 'Duragesic', 'Fentora', 'Hysingla', 'Methadose',
       'Morphabond', 'Nucynta ER', 'Onsolis', 'Oramorph', 'Oxaydo',
       'Roxanol-T', 'Sublimaze', 'Xtampza', 'Zohydro', 'Anexsia',
       'Co-Gesic', 'Embeda', 'Exalgo', 'Hycet', 'Hycodan', 'Hydromet',
       'Ibudone', 'Kadian', 'Liquicet', 'Lorcet', 'Lorcet Plus', 'Lortab',
       'Maxidone', 'MS Contin', 'Norco', 'Opana ER', 'OxyContin', 'Oxycet',
       'Palladone', 'Percocet', 'Percodan', 'Reprexain', 'Rezira',
       'Roxicet', 'Targiniq ER', 'TussiCaps', 'Tussionex', 'Tuzistra XR',
       'Tylenol 3', 'Tylenol 4', 'Vicodin', 'Vicodin ES', 'Vicodin HP',
       'Vicoprofen', 'Vituz', 'Xartemis XR', 'Xodol', 'Zolvit', 'Zutripro',
       'Zydone', 'Fentanyl', 'Methadone hydrochloride', 'Morphine sulfate',
       'Oxymorphone hydrochloride'], dtype=object)

In [11]:
#capitalize all drug names in searchlist b/c the product_name is all capitalized
cap_searchlist = [element.upper() for element in searchlist]

In [12]:
#make sure all the product_names are capitalized in the dataframe so we get everything 
cms_2017['product_name'] = map(lambda x: str(x).upper(), cms_2017['product_name'])

In [14]:
#now search through to find a match
cms_2017_opioids = cms_2017.query('product_name in @cap_searchlist')
print(cms_2017_opioids['product_name'].nunique()) #33
print(len(searchlist)) #65

33
65

In [15]:
#make a new column called 'PRODUCTNDC'
cms_2017_opioids['PRODUCTNDC'] = cms_2017_opioids['label_code'].astype(str) + '-' +cms_2017_opioids['product_code'].astype(str)

/Users/catherineordun/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
#check it's right
cms_2017_opioids.loc[(cms_2017_opioids["product_name"] == "ABSTRAL")] #ok it works

,Utilization Type,State,label_code,product_code,package_size,Year,Quarter,product_name,suppression,units_reimb,...,total_amt_reimb,med_amt_reimb,nonmed_amt_reimb,qtr_begin,qtr_begin_date,Latitude,Longitude,Location,NDC,PRODUCTNDC
1065170,FFSU,MO,57881,332,32,2017,2,ABSTRAL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,38.4623,-92.302,"(38.4623, -92.302)",57881033232,57881-332
2205338,FFSU,XX,57881,332,32,2017,2,ABSTRAL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,NaN,NaN,NaN,57881033232,57881-332

In [17]:
nda_product.loc[(nda_product["PRODUCTNDC"] == "409-1201")] #there are products in CMS that aren't in the NDA products

#for example, the above 409-1201 is demerol and demerol is not in the nda PRODUCTS table
cms_2017_opioids.loc[(cms_2017_opioids["PRODUCTNDC"] == "409-1201")] #ok it works

,Utilization Type,State,label_code,product_code,package_size,Year,Quarter,product_name,suppression,units_reimb,...,total_amt_reimb,med_amt_reimb,nonmed_amt_reimb,qtr_begin,qtr_begin_date,Latitude,Longitude,Location,NDC,PRODUCTNDC
34099,MCOU,KY,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",409120120,409-1201
304760,FFSU,SC,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,33.8191,-80.9066,"(33.8191, -80.9066)",409120120,409-1201
378029,FFSU,TN,409,1201,20,2017,1,DEMEROL,False,49.0,...,23.30,23.30,0.00,1/1,01/01/2017 12:00:00 AM,35.7449,-86.7489,"(35.7449, -86.7489)",409120120,409-1201
535681,MCOU,MN,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",409120120,409-1201
563779,MCOU,SC,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,33.8191,-80.9066,"(33.8191, -80.9066)",409120120,409-1201
616224,FFSU,NC,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",409120120,409-1201
658637,MCOU,TN,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,35.7449,-86.7489,"(35.7449, -86.7489)",409120120,409-1201
1029239,MCOU,MN,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,45.7326,-93.9196,"(45.7326, -93.9196)",409120120,409-1201
1035148,MCOU,SC,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,33.8191,-80.9066,"(33.8191, -80.9066)",409120120,409-1201
1116803,FFSU,NC,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,35.6411,-79.8431,"(35.6411, -79.8431)",409120120,409-1201
1318795,MCOU,KY,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,37.6690,-84.6514,"(37.669, -84.6514)",409120120,409-1201
1636942,FFSU,MI,409,1201,20,2017,1,DEMEROL,False,18.0,...,82.10,36.26,45.84,1/1,01/01/2017 12:00:00 AM,43.3504,-84.5603,"(43.3504, -84.5603)",409120120,409-1201
1901828,MCOU,TN,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,35.7449,-86.7489,"(35.7449, -86.7489)",409120120,409-1201
1991757,FFSU,AK,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,61.3850,-152.2683,"(61.385, -152.2683)",409120120,409-1201
2078793,FFSU,MI,409,1201,20,2017,2,DEMEROL,True,NaN,...,NaN,NaN,NaN,4/1,04/01/2017 12:00:00 AM,43.3504,-84.5603,"(43.3504, -84.5603)",409120120,409-1201
2120868,FFSU,TN,409,1201,20,2017,2,DEMEROL,False,16.0,...,4.07,4.07,0.00,4/1,04/01/2017 12:00:00 AM,35.7449,-86.7489,"(35.7449, -86.7489)",409120120,409-1201
2330619,FFSU,AK,409,1201,20,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,1/1,01/01/2017 12:00:00 AM,61.3850,-152.2683,"(61.385, -152.2683)",409120120,409-1201

<b>MERGE FDA AND CMS</b>

In [18]:
#MERGE WITH NDA PRODUCT DF
cms_2017_opioids_fin = pd.merge(cms_2017_opioids, nda_product, on='PRODUCTNDC', how='left')
#how many are missing
cms_2017_opioids_fin['PRODUCTID'].isnull().sum() #1840
len(cms_2017_opioids_fin) #5265 total records

5265

In [19]:
cms_2017_opioids_fin.head()

,Utilization Type,State,label_code,product_code,package_size,Year,Quarter,product_name,suppression,units_reimb,...,STARTMARKETINGDATE,ENDMARKETINGDATE,MARKETINGCATEGORYNAME,APPLICATIONNUMBER,LABELERNAME,SUBSTANCENAME,ACTIVE_NUMERATOR_STRENGTH,ACTIVE_INGRED_UNIT,PHARM_CLASSES,DEASCHEDULE
0,FFSU,MI,409,1256,1,2017,1,DEMEROL,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FFSU,MN,59011,460,10,2017,1,OXYCONTIN,False,961.0,...,20100808.0,NaN,NDA,NDA022272,Purdue Pharma LP,OXYCODONE HYDROCHLORIDE,60,mg/1,"Full Opioid Agonists [MoA],Opioid Agonist [EPC]",CII
2,FFSU,AK,63481,817,60,2017,1,OPANA ER,True,NaN,...,20120320.0,20191101.0,NDA,NDA201655,"Endo Pharmaceuticals, Inc.",OXYMORPHONE HYDROCHLORIDE,30,mg/1,"Full Opioid Agonists [MoA],Opioid Agonist [EPC]",CII
3,MCOU,LA,59011,751,4,2017,1,BUTRANS,True,NaN,...,20110214.0,NaN,NDA,NDA021306,Purdue Pharma LP,BUPRENORPHINE,10,ug/h,"Partial Opioid Agonist [EPC],Partial Opioid Ag...",CIII
4,FFSU,VT,50458,94,5,2017,1,DURAGESIC,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
cms_2017_opioids_fin.dtypes

Utilization Type              object
State                         object
label_code                     int64
product_code                   int64
package_size                   int64
Year                           int64
Quarter                        int64
product_name                  object
suppression                     bool
units_reimb                  float64
num_rx                       float64
total_amt_reimb              float64
med_amt_reimb                float64
nonmed_amt_reimb             float64
qtr_begin                     object
qtr_begin_date                object
Latitude                     float64
Longitude                    float64
Location                      object
NDC                            int64
PRODUCTNDC                    object
PRODUCTID                     object
PRODUCTTYPENAME               object
PROPRIETARYNAME               object
PROPRIETARYNAMESUFFIX         object
NONPROPRIETARYNAME            object
DOSAGEFORMNAME                object
ROUTENAME                     object
STARTMARKETINGDATE           float64
ENDMARKETINGDATE             float64
MARKETINGCATEGORYNAME         object
APPLICATIONNUMBER             object
LABELERNAME                   object
SUBSTANCENAME                 object
ACTIVE_NUMERATOR_STRENGTH     object
ACTIVE_INGRED_UNIT            object
PHARM_CLASSES                 object
DEASCHEDULE                   object
dtype: object

In [21]:
#convert startmarketingdate and endmarketingdate to datetime
#startdate
cms_2017_opioids_fin['STARTMARKETINGDATE'].fillna(value=0, inplace=True)
cms_2017_opioids_fin['STARTMARKETINGDATE'] = map(lambda x: int(x), cms_2017_opioids_fin['STARTMARKETINGDATE'])
cms_2017_opioids_fin['STARTMARKETINGDATE'] = cms_2017_opioids_fin['STARTMARKETINGDATE'].apply(str)
cms_2017_opioids_fin['startdate'] = map(lambda x: x[0:4] + "-" + x[4:6] + "-" + x[6:], cms_2017_opioids_fin['STARTMARKETINGDATE'])
cms_2017_opioids_fin['startdate'].replace(to_replace='0--', value='1970-01-01', inplace=True)
cms_2017_opioids_fin['startdate'] = pd.to_datetime(cms_2017_opioids_fin['startdate'], format='%Y-%m-%d')

In [22]:
#enddate
cms_2017_opioids_fin['ENDMARKETINGDATE'].fillna(value=0, inplace=True)
cms_2017_opioids_fin['ENDMARKETINGDATE'] = map(lambda x: int(x), cms_2017_opioids_fin['ENDMARKETINGDATE'])
cms_2017_opioids_fin['ENDMARKETINGDATE'] = cms_2017_opioids_fin['ENDMARKETINGDATE'].apply(str)
cms_2017_opioids_fin['enddate'] = map(lambda x: x[0:4] + "-" + x[4:6] + "-" + x[6:], cms_2017_opioids_fin['ENDMARKETINGDATE'])
cms_2017_opioids_fin['enddate'].replace(to_replace='0--', value='1970-01-01', inplace=True)
cms_2017_opioids_fin['enddate'] = pd.to_datetime(cms_2017_opioids_fin['enddate'], format='%Y-%m-%d')

In [23]:
cms_2017_opioids_fin.dtypes

Utilization Type                     object
State                                object
label_code                            int64
product_code                          int64
package_size                          int64
Year                                  int64
Quarter                               int64
product_name                         object
suppression                            bool
units_reimb                         float64
num_rx                              float64
total_amt_reimb                     float64
med_amt_reimb                       float64
nonmed_amt_reimb                    float64
qtr_begin                            object
qtr_begin_date                       object
Latitude                            float64
Longitude                           float64
Location                             object
NDC                                   int64
PRODUCTNDC                           object
PRODUCTID                            object
PRODUCTTYPENAME                      object
PROPRIETARYNAME                      object
PROPRIETARYNAMESUFFIX                object
NONPROPRIETARYNAME                   object
DOSAGEFORMNAME                       object
ROUTENAME                            object
STARTMARKETINGDATE                   object
ENDMARKETINGDATE                     object
MARKETINGCATEGORYNAME                object
APPLICATIONNUMBER                    object
LABELERNAME                          object
SUBSTANCENAME                        object
ACTIVE_NUMERATOR_STRENGTH            object
ACTIVE_INGRED_UNIT                   object
PHARM_CLASSES                        object
DEASCHEDULE                          object
startdate                    datetime64[ns]
enddate                      datetime64[ns]
dtype: object

this dataframe: cms_2017_opioids_fin is what's in the hackathon repo.

<b>Some key stats</b>

In [31]:
#Pivot Table with Key STats
cms17_stats = pd.pivot_table(cms_2017_opioids_fin,index=["State", "Quarter", "startdate","product_name", "DOSAGEFORMNAME", "LABELERNAME", "ROUTENAME", "DEASCHEDULE", "ACTIVE_NUMERATOR_STRENGTH"], 
                                values=['units_reimb', 'num_rx', 'total_amt_reimb', 
                                        'med_amt_reimb', 'nonmed_amt_reimb'], 
               aggfunc={'units_reimb': lambda x: x.sum(), 
                        'num_rx': lambda x: x.sum(), 
                        'total_amt_reimb': lambda x: x.sum(),
                        'med_amt_reimb': lambda x: x.sum(),
                        'nonmed_amt_reimb':lambda x: x.sum()})

cms17_stats_fin = cms17_stats.reset_index()
cms17_stats_fin.rename(columns={'units_reimb': 'units_reimb_sum', 
                                'num_rx':'num_rx_sum', 
                                'total_amt_reimb':'total_amt_reimb_sum',
                                'med_amt_reimb':'med_amt_reimb_sum',
                                'nonmed_amt_reimb':'nonmed_amt_reimb_sum'}, inplace=True)
cms17_stats_fin.reset_index(inplace=True)

After talking to a doctor friend of mine, figured out that ACTIVE_NUMERATOR_STRENGTH is the dosage.

In [32]:
cms17_stats_fin['strength'] = cms17_stats_fin['ACTIVE_NUMERATOR_STRENGTH'].str.split(';').str[0]
cms17_stats_fin['strength'].fillna(value=0, inplace=True)
cms17_stats_fin['strength'] = map(lambda x: float(x), cms17_stats_fin['strength'])

In [33]:
cms17_stats_fin.head()

,index,State,Quarter,startdate,product_name,DOSAGEFORMNAME,LABELERNAME,ROUTENAME,DEASCHEDULE,ACTIVE_NUMERATOR_STRENGTH,med_amt_reimb_sum,nonmed_amt_reimb_sum,num_rx_sum,total_amt_reimb_sum,units_reimb_sum,strength
0,0,AK,1,1956-01-01,DILAUDID,TABLET,Purdue Pharma LP,ORAL,CII,2,0.0,0.0,0.0,0.0,0.0,2.0
1,1,AK,1,1987-12-31,TUSSIONEX,"SUSPENSION, EXTENDED RELEASE",Unither Manufacturing LLC,ORAL,CII,10; 8,0.0,0.0,0.0,0.0,0.0,10.0
2,2,AK,1,1997-06-25,NORCO,TABLET,"Actavis Pharma, Inc.",ORAL,CII,5; 325,0.0,0.0,0.0,0.0,0.0,5.0
3,3,AK,1,2007-08-20,FENTANYL,PATCH,Par Pharmaceutical Inc.,TRANSDERMAL,CII,100,0.0,0.0,0.0,0.0,0.0,100.0
4,4,AK,1,2007-08-20,FENTANYL,PATCH,Par Pharmaceutical Inc.,TRANSDERMAL,CII,50,0.0,0.0,0.0,0.0,0.0,50.0

How much drugs have been reimbursed, providing us a proxy measure of legitimate hospital supply of drugs?  Multiply `units_reimb_sum` by `strength`.

In [34]:
cms17_stats_fin['legit_supply'] = cms17_stats_fin['units_reimb_sum'] * cms17_stats_fin['strength']
cms17_stats_fin.fillna(value=0, inplace=True)

In [35]:
supply_index_2017 = cms17_stats_fin[['State', 'Quarter', 'startdate','product_name', 'LABELERNAME', 'DOSAGEFORMNAME', 'ROUTENAME', 'legit_supply']]
supply_index_2017.head(25)

,State,Quarter,startdate,product_name,LABELERNAME,DOSAGEFORMNAME,ROUTENAME,legit_supply
0,AK,1,1956-01-01,DILAUDID,Purdue Pharma LP,TABLET,ORAL,0.0
1,AK,1,1987-12-31,TUSSIONEX,Unither Manufacturing LLC,"SUSPENSION, EXTENDED RELEASE",ORAL,0.0
2,AK,1,1997-06-25,NORCO,"Actavis Pharma, Inc.",TABLET,ORAL,0.0
3,AK,1,2007-08-20,FENTANYL,Par Pharmaceutical Inc.,PATCH,TRANSDERMAL,0.0
4,AK,1,2007-08-20,FENTANYL,Par Pharmaceutical Inc.,PATCH,TRANSDERMAL,0.0
5,AK,1,2007-08-20,FENTANYL,Par Pharmaceutical Inc.,PATCH,TRANSDERMAL,0.0
6,AK,1,2009-08-13,EMBEDA,Pfizer Laboratories Div Pfizer Inc,"CAPSULE, EXTENDED RELEASE",ORAL,0.0
7,AK,1,2009-08-13,EMBEDA,Pfizer Laboratories Div Pfizer Inc,"CAPSULE, EXTENDED RELEASE",ORAL,0.0
8,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,50340.0
9,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,37860.0
10,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,173200.0
11,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,198780.0
12,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,40440.0
13,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,285360.0
14,AK,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
15,AK,1,2011-02-14,BUTRANS,Purdue Pharma LP,"PATCH, EXTENDED RELEASE",TRANSDERMAL,1960.0
16,AK,1,2011-02-14,BUTRANS,Purdue Pharma LP,"PATCH, EXTENDED RELEASE",TRANSDERMAL,2880.0
17,AK,1,2011-02-14,BUTRANS,Purdue Pharma LP,"PATCH, EXTENDED RELEASE",TRANSDERMAL,4240.0
18,AK,1,2011-02-14,BUTRANS,Purdue Pharma LP,"PATCH, EXTENDED RELEASE",TRANSDERMAL,610.0
19,AK,1,2011-02-14,BUTRANS,Purdue Pharma LP,"PATCH, EXTENDED RELEASE",TRANSDERMAL,0.0
20,AK,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
21,AK,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
22,AK,1,2012-03-20,OPANA ER,"Endo Pharmaceuticals, Inc.","TABLET, EXTENDED RELEASE",ORAL,0.0
23,AK,1,2012-03-20,OPANA ER,"Endo Pharmaceuticals, Inc.","TABLET, EXTENDED RELEASE",ORAL,0.0
24,AK,1,2012-03-20,OPANA ER,"Endo Pharmaceuticals, Inc.","TABLET, EXTENDED RELEASE",ORAL,0.0

<b>Texas</b>

In [36]:
tx_supply = supply_index_2017.loc[(supply_index_2017['State'] == 'TX')]
tx_supply

,State,Quarter,startdate,product_name,LABELERNAME,DOSAGEFORMNAME,ROUTENAME,legit_supply
2046,TX,1,1987-07-01,MS CONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2047,TX,1,1987-07-01,MS CONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2048,TX,1,1987-12-31,TUSSIONEX,Unither Manufacturing LLC,"SUSPENSION, EXTENDED RELEASE",ORAL,0.0
2049,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,92640.0
2050,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,59160.0
2051,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,291320.0
2052,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,303660.0
2053,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,411680.0
2054,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,541380.0
2055,TX,1,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,804240.0
2056,TX,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,234000.0
2057,TX,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,126000.0
2058,TX,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2059,TX,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,240000.0
2060,TX,1,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,48000.0
2061,TX,2,1987-07-01,MS CONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2062,TX,2,1987-07-01,MS CONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2063,TX,2,1987-07-01,MS CONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2064,TX,2,1987-12-31,TUSSIONEX,Unither Manufacturing LLC,"SUSPENSION, EXTENDED RELEASE",ORAL,0.0
2065,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,83100.0
2066,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,50190.0
2067,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,265540.0
2068,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,287340.0
2069,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,335480.0
2070,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,477840.0
2071,TX,2,2010-08-08,OXYCONTIN,Purdue Pharma LP,"TABLET, FILM COATED, EXTENDED RELEASE",ORAL,590160.0
2072,TX,2,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,312900.0
2073,TX,2,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,130500.0
2074,TX,2,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0
2075,TX,2,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,209500.0
2076,TX,2,2011-08-25,NUCYNTA ER,"Janssen Pharmaceuticals, Inc.","TABLET, FILM COATED, EXTENDED RELEASE",ORAL,0.0

<b>CMS 2016 Data</b>

In [ ]:
cms_2016 = pd.read_csv("/Users/catherineordun/Documents/Hackathon/DHHS/ready_data/State_Drug_Utilization_Data_2016.csv")
print(cms_2016.shape) #(4625479, 20)
cms_2016.rename(columns={
        'Labeler Code':'label_code',
        'Product Code':'product_code',
        'Package Size':'package_size',
        'Product Name':'product_name',
        'Suppression Used':'suppression',
        'Units Reimbursed':'units_reimb',
        'Number of Prescriptions':'num_rx',
        'Total Amount Reimbursed':'total_amt_reimb',
        'Medicaid Amount Reimbursed':'med_amt_reimb',
        'Non Medicaid Amount Reimbursed':'nonmed_amt_reimb',
        'Quarter Begin':'qtr_begin', 
        'Quarter Begin Date':'qtr_begin_date'},inplace=True)

#make sure all the product_names are capitalized in the dataframe so we get everything 
cms_2016['product_name'] = map(lambda x: str(x).upper(), cms_2016['product_name'])

#now search through to find a match
cms_2016_opioids = cms_2016.query('product_name in @cap_searchlist')
print(cms_2016_opioids['product_name'].nunique()) #33

#make a new column called 'PRODUCTNDC'
cms_2016_opioids['PRODUCTNDC'] = cms_2016_opioids['label_code'].astype(str) + '-' +cms_2016_opioids['product_code'].astype(str)

#check it's right
cms_2016_opioids.loc[(cms_2016_opioids["product_name"] == "ABSTRAL")] #ok it works
#MERGE WITH NDA PRODUCT DF
cms_2016_opioids_fin = pd.merge(cms_2016_opioids, nda_product, on='PRODUCTNDC', how='left')
len(cms_2016_opioids_fin) #11287
cms_2016_opioids_fin['PRODUCTID'].isnull().sum() #4039

#convert startmarketingdate and endmarketingdate to datetime
#startdate
cms_2016_opioids_fin['STARTMARKETINGDATE'].fillna(value=0, inplace=True)
cms_2016_opioids_fin['STARTMARKETINGDATE'] = map(lambda x: int(x), cms_2016_opioids_fin['STARTMARKETINGDATE'])
cms_2016_opioids_fin['STARTMARKETINGDATE'] = cms_2016_opioids_fin['STARTMARKETINGDATE'].apply(str)
cms_2016_opioids_fin['startdate'] = map(lambda x: x[0:4] + "-" + x[4:6] + "-" + x[6:], cms_2016_opioids_fin['STARTMARKETINGDATE'])
cms_2016_opioids_fin['startdate'].replace(to_replace='0--', value='1970-01-01', inplace=True)
cms_2016_opioids_fin['startdate'] = pd.to_datetime(cms_2016_opioids_fin['startdate'], format='%Y-%m-%d')

#enddate
cms_2016_opioids_fin['ENDMARKETINGDATE'].fillna(value=0, inplace=True)
cms_2016_opioids_fin['ENDMARKETINGDATE'] = map(lambda x: int(x), cms_2016_opioids_fin['ENDMARKETINGDATE'])
cms_2016_opioids_fin['ENDMARKETINGDATE'] = cms_2016_opioids_fin['ENDMARKETINGDATE'].apply(str)
cms_2016_opioids_fin['enddate'] = map(lambda x: x[0:4] + "-" + x[4:6] + "-" + x[6:], cms_2016_opioids_fin['ENDMARKETINGDATE'])
cms_2016_opioids_fin['enddate'].replace(to_replace='0--', value='1970-01-01', inplace=True)
cms_2016_opioids_fin['enddate'] = pd.to_datetime(cms_2016_opioids_fin['enddate'], format='%Y-%m-%d')
#send to csv
#cms_2016_opioids_fin.to_csv("/Users/catherineordun/Documents/Hackathon/DHHS/final_datasets/cms_2016_opioids_fin.csv")
#Pivot Table with Key STats
cms16_stats = pd.pivot_table(cms_2016_opioids_fin,index=["State", "Quarter", "product_name", "DOSAGEFORMNAME", "LABELERNAME", "ROUTENAME", "DEASCHEDULE", "ACTIVE_NUMERATOR_STRENGTH"], 
                                values=['units_reimb', 'num_rx', 'total_amt_reimb', 
                                        'med_amt_reimb', 'nonmed_amt_reimb'], 
               aggfunc={'units_reimb': lambda x: x.sum(), 
                        'num_rx': lambda x: x.sum(), 
                        'total_amt_reimb': lambda x: x.sum(),
                        'med_amt_reimb': lambda x: x.sum(),
                        'nonmed_amt_reimb':lambda x: x.sum()})

cms16_stats_fin = cms16_stats.reset_index()
cms16_stats_fin.rename(columns={'units_reimb': 'units_reimb_sum', 
                                'num_rx':'num_rx_sum', 
                                'total_amt_reimb':'total_amt_reimb_sum',
                                'med_amt_reimb':'med_amt_reimb_sum',
                                'nonmed_amt_reimb':'nonmed_amt_reimb_sum'}, inplace=True)
cms16_stats_fin.reset_index(inplace=True)
    
cms16_stats_fin['strength'] = cms16_stats_fin['ACTIVE_NUMERATOR_STRENGTH'].str.split(';').str[0]
cms16_stats_fin['strength'].fillna(value=0, inplace=True)
cms16_stats_fin['strength'] = map(lambda x: float(x), cms16_stats_fin['strength'])

In [ ]:
cms16_stats_fin.head()